/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Find the first window matching the title */
export declare function findWindowByTitle(title: string, exact?: boolean | undefined | null): WindowInfo | null

/**
 * Find windows by title (supports partial matching)
 * If `exact` is true, only returns windows with exact title match
 * If `exact` is false, returns windows containing the search string
 */
export declare function findWindowsByTitle(title: string, exact?: boolean | undefined | null): Array<WindowInfo>

/** Get window info by handle */
export declare function getWindowInfo(handle: unknown): WindowInfo | null

/** Get all visible windows */
export declare function getWindows(): Array<WindowInfo>

/** Check if click-through is currently enabled for a window */
export declare function isClickThrough(handle: unknown): boolean

/** Disable click-through on a window (window captures mouse events again) */
export declare function removeClickThrough(handle: unknown): void

/** Make a window always on top */
export declare function setAlwaysOnTop(handle: unknown, onTop: boolean): void

/** Enable click-through on a window (mouse events pass through) */
export declare function setClickThrough(handle: unknown): void

/** Set window transparency/opacity (0.0 = fully transparent, 1.0 = fully opaque) */
export declare function setWindowOpacity(handle: unknown, opacity: number): void

/**
 * Toggle click-through state on a window
 * Returns the new state: true = click-through enabled, false = disabled
 */
export declare function toggleClickThrough(handle: unknown): boolean

/** Represents information about a window */
export interface WindowInfo {
  /** Window handle (HWND on Windows, Window ID on X11, NSWindow pointer on macOS) */
  handle: number
  /** Window title */
  title: string
  /** Process ID that owns the window */
  processId: number
  /** Window class name (Windows only, empty on other platforms) */
  className: string
  /** Whether the window is visible */
  visible: boolean
  /** Window position X */
  x: number
  /** Window position Y */
  y: number
  /** Window width */
  width: number
  /** Window height */
  height: number
}
